### ISSUE TITLE
Error: Couldn't read data for number : EOF. Is the number properly registered?

### ISSUE THREAD

**Issue by kamgiel** [haberda/signal-addon#112]
Hey!

So something has happened.
My addon is not working and there is a lot of:
time="2023-11-11T22:29:35+01:00" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
in my log.
Everything was working fine until last week. 

Probably the problem was figured out by bbernhard [here](https://github.com/bbernhard/signal-cli-rest-api/issues/340)

Any chance to fix the addon?
Thanks!

**Comment by dan-s-github** [comment]
I documented how to fix this in add-on here: https://github.com/bbernhard/signal-cli-rest-api/issues/444#issuecomment-1806989305
Maybe I should have documented it here though.

**Comment by haberda** [comment]
> Hey!
> 
> So something has happened.
> My addon is not working and there is a lot of:
> time="2023-11-11T22:29:35+01:00" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
> in my log.
> Everything was working fine until last week. 
> 
> Probably the problem was figured out by bbernhard [here](https://github.com/bbernhard/signal-cli-rest-api/issues/340)
> 
> Any chance to fix the addon?
> Thanks!

The add-on is just the bbernhard docker image repackaged, so it cannot be fixed until the next bbernhard release.

**Comment by kamgiel** [comment]
Hi!
Since there was a new release of bbernhards app is there a chance to upgrade yours? :)

Kamil

**Comment by haberda** [comment]
I think this is resolved, so I will close. Re-open if not.
