### ISSUE TITLE
instructions for adding desktop app

### ISSUE THREAD

**Issue by steveredden** [haberda/signal-addon#12]
install desktop app
use a qr scanner app on a phone to translate QR to URI
install/run portainer on HASS
open console on addon_signal_messenger container
```
su signal-api
signal-cli --config /data -u "+15555555555" addDevice --uri "sgnl://linkdevice?uuid=xyz&pub_key=xyz2"
```

**Comment by haberda** [comment]
Thanks, I'll add a link to the readme

**Comment by shalak** [comment]
I worked around this by killing the java process inside the container. The desktop app started showing the "contacts synchronisation popup" and looked stuck. I then run `signal-cli --config /config -u '+ACCOUNT_NUMBER' sendContacts` and it started to work OK. I had to restart the add-on afterwards to bring back the java process of course.
