### ISSUE TITLE
Unable to start container - Directory not empty

### ISSUE THREAD

**Issue by steveredden** [haberda/signal-addon#124]
Getting the following when attempting to start the add-on:

```
mv: inter-device move failed: '/data/data' to '/config/data'; unable to remove target: Directory not empty
```

**Comment by steveredden** [comment]
I got around this by

1. Backing up my `../addon_configs/*_signal_messenger` directory
2. Deleting `../addon_configs/*_signal_messenger/data` directory
3. Starting the container
4. Replacing the `/data` directory
5. Restarting the container

**Comment by haberda** [comment]
Yeah, I wrote some basic logic to try and migrate the configs over, but obviously not perfect. Glad you got it working.
