### ISSUE TITLE
signal_messenger service not starting with "inter-device move..." errors in log after upgrading from 0.85 to 0.86

### ISSUE THREAD

**Issue by soleous** [haberda/signal-addon#153]
I created the following on home-assistant core: https://github.com/home-assistant/core/issues/123361, but is this a better place as its addon related?

After upgrading from 0.85 to 0.86, the service will not start with the following in the log files:

> mv: inter-device move failed: '/data/data' to '/config/data'; unable to remove target: Directory not empty

Mitigated by restoring back to 0.85, but after retesting upgrade back to 0.86, the problem persists.

**Comment by haberda** [comment]
Should be fixed in 0.88.0

**Comment by soleous** [comment]
Can confirm its fix in 0.88.  Thanks for sorting this.
