### ISSUE TITLE
 Home Assistant - Increase in diskspace over time, or until next restart of Signal add-on

### ISSUE THREAD

**Issue by henriklund** [haberda/signal-addon#155]
I have noted over the past week that disk space used keeps growing. However, after system reboot everything is back at the expected level, only to start anew.
Investigation have shown that this is occurring in relation to the signal add-on and specifically files stored in the /tmp folder. Some time after restart of the add-on, a picture similar to following can be seen:

![image](https://github.com/user-attachments/assets/d25982b6-8bb9-4589-b1d1-afd2db38cfc4)

From time to time, following _may_ be seen around the same in the add-ons log:

![image](https://github.com/user-attachments/assets/6f6f652d-1d0d-41f5-962b-8d8bd91fb457)

The odd part is that a) Signal is used a receiver (it only triggers SEND message when having received a message from a specific recipient), b) default settings are applied to add-on and c) aside from the occasional update of the add-on, the usage of this add-on is very low.

Behaviour is applicable on v.83 and onwards (I have no stored backups with older versions).

**Comment by haberda** [comment]
I don't do anything to modify the upstream container that would effect what you are seeing. All I really do is change a few environment variables as documented in the upstream to make it easier to deploy on HASS. So the short answer is I don't know why you are seeing what you are seeing. 

My /tmp dir in the container only has one copy of the sqlite database and I run the add-on for weeks at a time in between restarts. It is only 1mb. Which mode do you run in? I am always in json-rpc.
