### ISSUE TITLE
QR Code - 'Device approved' but doesn't work.

### ISSUE THREAD

**Issue by Yersi88** [haberda/signal-addon#24]
Sorry I couldn't really figure out if this was an issue with addon or not :( 

I generated QR code with this command: http://192.168.100.156:8080/v1/qrcodelink?device_name=homeass 
Scanned it with the app. 
Got message: Device approved! 
However, the device does not show up in the 'linked devices' section of the app. 
And when I try to send notification with addon, nothing happens. 

What could I do to fix this ?

**Comment by haberda** [comment]
I don't develop the app, I just package it for use in home assistant, so I don't really know what is going on under the hood. There are links to the upstream project in the documentation of this project.

**Comment by Yersi88** [comment]
Alright! I created issue on rest api instead!
