### ISSUE TITLE
Constant high CPU for the addon

### ISSUE THREAD

**Issue by EDelsman** [haberda/signal-addon#43]
The signal messenger addon uses a constant 26% of CPU resources, while all my other addons use barely no CPU resources whatsoever. No notifications are being sent at the times that I checked. The percentage remais, even after restats and waiting and coming back to the addon later on.

Platform is an RPI4, running version 0.59.0 using json-rpc mode and running on HA version 2022.5.3

**Comment by haberda** [comment]
Hi. I haven't seen this issue, I'm running the same setup. Is this a fresh install, or is it configured? Do you have groups, or do anything else with the rest api? I don't do much to the upstream container, I just set some environment variables.

Can you make a backup and then wipe the container data, see if it has high usage then?

**Comment by EDelsman** [comment]
I feel silly because I forgot step one in case of any trouble: check the logs. There are constant error messages with regard to a phone number I entered incorrectly (left out the area code). I checked my notifier section in configuration.yaml but the wrong number isn't there, I do have a working notification, su I guess I first tried to register my phone number without the area code, then "corrceted" my mistake by trying again with the right one. So the big question is: can I unregister the wrong phone number with the rest API wityhout needing to go through the hassle of registering the right one all over again?

**Comment by EDelsman** [comment]
I put in an issue with the Signal api to ask for a way to remove the bad phonenumer, this issue can be closed as I think it is caused by the rest api itself and not the addon itself.

**Comment by EDelsman** [comment]
I would still like a way to remove unwanted phone numbers that are not/no longer registered with Signal on HAOS, where there is no access to files in docker.

**Comment by EDelsman** [comment]
I still closed it as I now realize this is not the right place.
