### ISSUE TITLE
Use latest upstream version

### ISSUE THREAD

**Issue by speedst3r** [haberda/signal-addon#58]
The current add-on version is using 0.60 from upstream. The current upstream release is 0.62, and there will be an update shortly to address https://github.com/bbernhard/signal-cli-rest-api/issues/286 

My add-on is experiencing this issue. With the add-on in "normal" mode, the following code allows it to resume operation

```
apt update && apt install -y zip unzip && \
cd /opt/signal-cli-0.10.8/lib/ && \
mkdir tmp && \
cd tmp/ && \
unzip ../signal-cli-0.10.8.jar && \
sed -i 's/Signal-Android\/5.22.3/Signal-Android\/5.51.7/g' org/asamk/signal/BaseConfig.class && \
zip -r ../signal-cli-0.10.8.jar org/ META-INF/ && \
cd .. && \
rm -rf tmp/ && \
exit
```

Can the HA addon please be brought up to date with upstream (when the upstream issue is resolved)?

**Comment by aneisch** [comment]
#59 will resolve.
