### ISSUE TITLE
Pairing an Android device is not possible

### ISSUE THREAD

**Issue by raebbaer** [haberda/signal-addon#82]
I installed the signal addon on a new HA installation. Then I tried to register my number using: 

curl -X GET -H "Content-Type: application/json" 'http://homeassistant.local:8080/v1/qrcodelink?device_name=signalapi' --output qr.png

I can scan the resulting QR code with my signal app on android and it says: Device paired. But if I look into the paired devices menu there is nothing to see. And the HA installation says: User not registered.

What do I do wrong?

**Comment by haberda** [comment]
This sounds like an upstream issue. I don't know how the Signal cli application works, I just packaged the upstream container for HAOS so that you can run it without a separate machine running docker. 

I would ask the question on that repository.

**Comment by raebbaer** [comment]
Thank you very much. I will ask on that repository.

**Comment by raebbaer** [comment]
I solved this issue using a different android phone with another signal installation...
